on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
    - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Install apt-utils
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-utils

      - name: Setup NVM and Node.js version 18.17.0
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
          nvm install 18.17.0
          nvm use 18.17.0
          nvm alias default 18.17.0

      - name: Check Node.js version
        run: |
          version=$(node -v)
          if [[ "$version" != v18.* ]]; then
            echo "Node.js version is $version but v18.x was expected. Halting the workflow."
            exit 1
          fi
        shell: bash

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install Dependencies with PNPM
        run: pnpm install

      - name: Build with PNPM
        run: pnpm run build
        
      - name: Build with PNPM
        run: pnpm run start
        
      - name: Package Application for Deployment
        run: |
          zip -r app.zip . -x "*.git*" "*node_modules*" "*.github*" "*__tests__*" "*logs*"
      
      - name: Deploy to Azure Web App
        id: deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'MinorityReport2'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_e87582fc4abb40ef9cfd5ab6fc80be88 }}
          package: './app.zip'
          
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: azure/webapps-deploy@v2
        with:
          action: "close"

