name: Build and deploy Node.js app to Azure Web App - MinorityReport3

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Install apt-utils
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-utils

      - name: Setup NVM and Node.js version 18.17.0
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
          nvm install 18.17.0
          nvm use 18.17.0
          nvm alias default 18.17.0

      - name: Check Node.js version
        run: |
          version=$(node -v)
          if [[ "$version" != v18.* ]]; then
            echo "Node.js version is $version but v18.x was expected. Halting the workflow."
            exit 1
          fi

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install Dependencies with PNPM
        run: pnpm install

      # Explicitly install Next.js dependencies
      - name: Install Next.js
        run: npm install next react react-dom

      - name: Build with PNPM
        run: pnpm run build

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r -x "node_modules/*" -x "*.git*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'MinorityReport3'
          slot-name: 'Production'
          package: .

